version: 2
builds:
  - id: obsid
    binary: obsid
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: obsid
    homepage: https://github.com/DylanSatow/obsid/
    repository:
      owner: DylanSatow
      name: homebrew-formulae
    commit_author:
      name: DylanSatow
      email: dylansatow531@gmail.com

checksum:
  name_template: "checksums.txt"
